apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookserver
  template:
    metadata:
      labels:
        app: bookserver
    spec:
      serviceAccountName: {{.Values.name}}
      containers:
        - name: {{.Values.name}}
          image: "{{.Values.image.repository}}:{{.Values.image.tag}}"